runtime: go125
automatic_scaling:
  max_instances: 5

handlers:
  - url: /images
    static_dir: images
    secure: always
    redirect_http_response_code: 301

  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
